# Generated by Django 3.0.5 on 2020-04-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('counties', models.CharField(max_length=30)),
                ('cases', models.CharField(max_length=30)),
                ('deaths', models.CharField(max_length=30)),
            ],
        ),
    ]
